### ISSUE TITLE
Add 404 Error Page

### ISSUE THREAD

**Issue by deavmi** [deavmi/deavmi.github.io-offline#7]
Add a 404 Error Page.

**Comment by Walkman100** [comment]
What should it look like? As an example, here is mine: http://walkman100.github.io/gaudcguixgfoeiu

**Comment by Walkman100** [comment]
Is this ok: https://deavmi.github.io/egcoiugfeie
I simply copied the header and footer HTML code from the index.html, with my 404 page text in between (changed the links of course)

**Comment by deavmi** [comment]
yep https://deavmi.github.io/egcoiugfeie is great. Thanks man. :D
